# Generated by Django 5.2.13 on 2026-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_label',
            field=models.CharField(blank=True, help_text='Örn: Part1 - Track 2 - sadece sınav çıktısında görünür. ', max_length=50, null=True),
        ),
    ]
