# Generated by Django 5.2.13 on 2026-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_audio_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.CharField(blank=True, help_text='Fill in the Blank tipi için', max_length=50, null=True),
        ),
    ]
