# Generated by Django 5.2.13 on 2026-07-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_mathingpair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MathingPair',
            new_name='MatchingPair',
        ),
    ]
