# Generated by Django 5.2.13 on 2026-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_mathingpair_matchingpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mc', 'Multiple Choices'), ('tf', 'True - False'), ('fib', 'Fill in the Blank'), ('matching', 'Matching'), ('open_ended', 'Open Ended')], default='mc', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('general', 'General'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='word_count_instruction',
            field=models.CharField(blank=True, help_text='Örn: 150 kelime yazın - Sadece Open Ended Questions için', max_length=100, null=True),
        ),
    ]
