# Generated by Django 5.2.13 on 2026-07-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
