# Generated by Django 5.2.13 on 2026-08-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_exam_questions_examquestion'),
        ('questions', '0007_question_image_label_alter_question_image_passage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamQuestion', to='questions.question'),
        ),
    ]
